pipeline {
    agent {
        docker {
            image 'maven:3.5.3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
       stage('Pub') {
            steps {
                 docker 'frolvlad/alpine-oraclejdk8:slim'
                 args '-v /root/.m2/repository/com/mysoft/log-test/1.0.0/:/data'
                 sh 'java -jar  /data/log-test-1.0.0.jar --server.port=8081'
            }
         }
    }
}
