pipeline {
    agent {
        docker {
            image 'maven:3.5.3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
         stage('构建镜像'){
             steps {
               echo "start build image"
              //build镜像
                bat 'docker build -t springboot-demo:1.0 .'

            }
        }

    }
}
